version: '3.8'

services:

  db:
    image: postgres
    ports:
      - "5432:5432"
    restart: always
    environment:
      POSTGRES_DB: springdata_jpa_postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: pass